"""create all tables

Revision ID: 20b689f7ab06
Revises: 
Create Date: 2026-05-24 17:29:38.594571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20b689f7ab06'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecast_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('market', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('forecast_date', sa.DateTime(), nullable=False),
    sa.Column('model_run_timestamp', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historical_prices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('market', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('datetime_block', sa.DateTime(), nullable=False),
    sa.Column('purchase_bid_mw', sa.Float(), nullable=True),
    sa.Column('sell_bid_mw', sa.Float(), nullable=True),
    sa.Column('mcv_mw', sa.Float(), nullable=True),
    sa.Column('final_scheduled_volume_mw', sa.Float(), nullable=True),
    sa.Column('mcp_rs_mwh', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('raw_mcp_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('market', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('datetime_block', sa.DateTime(), nullable=False),
    sa.Column('purchase_bid_mw', sa.Float(), nullable=True),
    sa.Column('sell_bid_mw', sa.Float(), nullable=True),
    sa.Column('mcv_mw', sa.Float(), nullable=True),
    sa.Column('final_scheduled_volume_mw', sa.Float(), nullable=True),
    sa.Column('mcp_rs_mwh', sa.Float(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_weather_forecasts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('datetime_hour', sa.DateTime(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('cloud_cover', sa.Float(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('solar_irradiance', sa.Float(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scrape_run_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('rows_written', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forecasts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('forecast_run_id', sa.UUID(), nullable=False),
    sa.Column('market', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('datetime_block', sa.DateTime(), nullable=False),
    sa.Column('predicted_price', sa.Float(), nullable=False),
    sa.Column('lower_ci', sa.Float(), nullable=True),
    sa.Column('upper_ci', sa.Float(), nullable=True),
    sa.Column('confidence_level', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['forecast_run_id'], ['forecast_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'standard', name='userrole'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'active', 'disabled', name='userstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('export_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('export_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('export_jobs')
    op.drop_table('users')
    op.drop_table('forecasts')
    op.drop_table('scrape_run_logs')
    op.drop_table('raw_weather_forecasts')
    op.drop_table('raw_mcp_snapshots')
    op.drop_table('organizations')
    op.drop_table('historical_prices')
    op.drop_table('forecast_runs')
    # ### end Alembic commands ###
